In [1]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import random
np.random.seed(10)
from sklearn.neighbors import KNeighborsRegressor

In [22]:
def load_data(string,path='../Datasets for Mid Sem Presentation/'):
    X = np.load(path+string+"_x.npy")
    y = np.load(path+string+"_y.npy")
    
    return X,y
        
    
def relative_cost(truth,pred):
    return np.mean(abs(pred-truth)/(1+truth))





def abs_error(pred,truth):
    return np.mean(np.abs(pred-truth))

In [23]:
test_x,test_y = load_data('test_data')
train_x,train_y = load_data("train_data_2")
v_x,v_y = load_data("val_data_2")

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
model = LinearRegression()
model.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [26]:
pred_train = model.predict(train_x)
pred_v = model.predict(v_x)
pred_test = model.predict(test_x)

In [27]:
train_cost = relative_cost(train_y,pred_train)
v_cost = relative_cost(v_y,pred_v)
test_cost = relative_cost(test_y,pred_test)

In [28]:
train_x[0].sum()

935056.8

In [29]:
train_cost,test_cost,v_cost

(0.7769037, 1.2031565, 1.4142147)

In [30]:
train_cost = abs_error(train_y,pred_train)
v_cost = abs_error(v_y,pred_v)
test_cost = abs_error(test_y,pred_test)

In [31]:
train_cost,test_cost,v_cost

(273.1952, 469.8713, 536.3746)

# Another Regression


Input Parameters are Bills of the Thirty Days, Hour Number and Day Number.
Output if the  Bill of the House of that Hour on that Day

In [32]:
def transformer(X,y):
    lst1=[]
    lst2=[]
    for train_example_number in range(len(X)):
        cnt=0
        for day in range(28):
            for hour in range(24):
                days_data = X[train_example_number]
                
                aug_data = np.concatenate((days_data,np.array([day]),np.array([hour])),axis=0)
                lst1.append(aug_data)
                lst2.append(y[train_example_number][cnt])
                cnt+=1
    return np.array(lst1),np.array(lst2)
            

In [33]:
final_x,final_y = transformer(train_x,train_y)
final_v_x,finalv_y = transformer(v_x,v_y)
final_test_x,final_test_y = transformer(test_x,test_y)
print (final_x.shape)

(57792, 30)


In [34]:
model = None
model = LinearRegression()
model.fit(final_x,final_y)
'''
print ("Error is "+str(relative_cost(model.predict(final_v_x),finalv__y+1)))
print ("Input shape is ",final_x.shape,' Output shape is ',final_y.shape)
errors1 = model.predict(final_test_x)-final_test_y
np.savetxt('results/simple_lin_reg_with_date_day.txt',errors1.flatten())'''

'\nprint ("Error is "+str(relative_cost(model.predict(final_v_x),finalv__y+1)))\nprint ("Input shape is ",final_x.shape,\' Output shape is \',final_y.shape)\nerrors1 = model.predict(final_test_x)-final_test_y\nnp.savetxt(\'results/simple_lin_reg_with_date_day.txt\',errors1.flatten())'

In [35]:
pred_train = model.predict(final_x)
pred_v = model.predict(final_v_x)
pred_test = model.predict(final_test_x)

In [36]:
train_cost = relative_cost(final_y,pred_train)
v_cost = relative_cost(finalv_y,pred_v)
test_cost = relative_cost(final_test_y,pred_test)

In [37]:
train_cost,test_cost,v_cost

(1.1423543485050982, 0.9793725849780432, 1.2012992873287438)

In [38]:
train_cost = abs_error(final_y,pred_train)
v_cost = abs_error(finalv_y,pred_v)
test_cost = abs_error(final_test_y,pred_test)

In [39]:
train_cost,test_cost,v_cost

(426.4133534147922, 417.05151378956043, 456.90617561886535)

# Temperature Included

Input Parameters are Bills of Thirty Days, Temperature of that Day(Min,Max,Avg), Day Number and Hour Number
Output is the bill of the house on that Day of that hour

In [22]:
temp_matrix = temp_data.as_matrix()[:,1:]
temp_matrix[0]

/home/rithwik/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


array([80, 88, 71])

In [35]:
final_x,final_y = transformer(train_x,train_y,temp_matrix)
final_test_x,final_test_y = transformer(test_x,test_y,temp_matrix)
final_v_x,final_v_y = transformer(v_x,v_y,temp_matrix)

In [36]:
model = LinearRegression()
model.fit(final_x,final_y)
final_x[0]

array([18014.8671875 , 20123.55078125, 20119.16601562, 12399.73339844,
       11603.09960938, 13713.6171875 , 15873.1171875 , 31440.46679688,
       17168.16601562, 14865.59960938, 16862.93359375, 16447.59960938,
       15743.56640625, 29077.1328125 , 15671.91699219, 15939.75      ,
       15110.61621094, 20880.53320312, 20445.96679688, 12451.20019531,
       17529.06640625, 14871.96679688, 16709.56640625, 19230.19921875,
       15375.03320312, 15327.43359375, 15329.54980469, 18790.75      ,
        9231.79980469, 17706.515625  ,    80.        ,    88.        ,
          71.        ,     0.        ,     0.        ])

In [37]:
model.coef_


array([ 1.38888899e-03,  1.38888882e-03,  1.38888916e-03,  1.38888888e-03,
        1.38888895e-03,  1.38888877e-03,  1.38888878e-03,  1.38888877e-03,
        1.38888924e-03,  1.38888910e-03,  1.38888850e-03,  1.38888872e-03,
        1.38888889e-03,  1.38888895e-03,  1.38888898e-03,  1.38888889e-03,
        1.38888888e-03,  1.38888868e-03,  1.38888899e-03,  1.38888865e-03,
        1.38888922e-03,  1.38888867e-03,  1.38888892e-03,  1.38888907e-03,
        1.38888906e-03,  1.38888856e-03,  1.38888924e-03,  1.38888881e-03,
        1.38888882e-03,  1.38888877e-03,  1.68329864e+00,  1.19154732e+01,
        1.07288709e+01, -1.48092504e+00,  2.02476358e-01])

In [38]:
preds = model.predict(final_test_x)
errors1 = model.predict(final_test_x)-final_test_y
np.savetxt('results/simple_lin_reg_with_date_day_temp.txt',errors1.flatten())


In [41]:
preds =  model.predict(final_v_x)

In [42]:
print ("After the New Params cost is ",relative_cost(preds,(final_v_y+1)))


('After the New Params cost is ', 0.9039316995193615)


# Hourly Prediction Model


In [43]:
models=[]
for i in range(24):
    indices = np.where(final_x[:,-1]==i,True,False)
    data_x = final_x[indices]
    data_y = final_y[indices]
    model = LinearRegression()
    model.fit(data_x,data_y)
    models.append(model)
    
    
    

In [51]:
errors = []
arr_to_write=np.zeros((v_y.shape))

for i in range(24):
    indices = np.where(v_x[:,-1]==i,True,False)
    data_x = v_x[indices]
    data_y = v_y[indices]
    model = models[i]
    if len(data_x)>0:
    
    pred = model.predict(data_x)
    curr_error = relative_cost(pred,(data_y+1))
    for j in range(30):
        arr_to_write[:,i+j*24] = pred[j::30]
    
    errors.append(curr_error)
    


0


ValueError: Found array with 0 sample(s) (shape=(0, 30)) while a minimum of 1 is required.

In [49]:
print ("Relative Cost is",np.mean(errors))

('Relative Cost is', 0.875634804089325)


In [227]:
model.coef_.shape,final_x.shape

((35,), (74880, 35))

In [228]:
np.array(arr_to_write).shape

(25, 720)

In [229]:
24*750

18000

In [230]:
750/25

30

In [231]:
test_x.shape

(25, 30)

In [232]:
relative_cost(arr_to_write,test_y+1)

1.1243433318216676

In [233]:
pred[j::30].shape

(25,)

In [234]:
arr_to_write[:,i+j*24:i+(j+1)*24].shape

(25, 1)

In [235]:
arr_to_write[0]

array([2568.67978802, 2284.28651822, 2504.45605084, 2471.63102531,
       1803.15810444, 1289.96747976,  914.95202484,  859.56314339,
        723.63915163,  816.63581349,  796.08591709,  887.50321814,
       1078.82401751, 1568.57186348, 1388.37523415, 1460.9783394 ,
       1807.64253583, 1834.09904186, 2113.75704247, 2106.21509755,
       2185.84966254, 2423.87603583, 2630.0036633 , 2868.53922634,
       2610.86352006, 2332.24502935, 2588.35379883, 2551.85768914,
       1867.62688639, 1330.09496193,  973.29316511,  911.47950481,
        755.10204118,  844.01561596,  829.11044001,  899.87366054,
       1105.03552808, 1595.59303644, 1454.72530378, 1558.05302777,
       1900.22897925, 1952.41095609, 2246.67476087, 2248.0952748 ,
       2306.72808451, 2541.98956796, 2733.28677983, 2966.60045213,
       2596.39070779, 2324.76118832, 2582.76561471, 2551.62314099,
       1866.17762535, 1340.72954629,  980.98815008,  922.41014816,
        770.5870861 ,  863.27146313,  843.59634824,  915.04626

In [236]:
np.savetxt('results/lin_reg_with_temp_hourly_model',(arr_to_write - test_y).flatten())

In [237]:
pred[j::30]

array([3011.15133225,  946.53374253,  495.96826399, 1099.7132381 ,
        822.14764403,  725.12898407, 1156.95562567,  855.70930198,
       2614.55768314, 1065.12048582, 1436.08926893, 1281.61091434,
       1210.82774839, 1039.34746079,  965.38170038, 1846.71223547,
        464.19144891, 1169.26210603,  891.74066523, 4185.37799903,
       1063.83521892, 2702.40701217, 4152.36601128,  869.16285419,
        358.21026002])

In [22]:
final_x.shape

(74880, 35)

In [24]:
data_x.shape

(3120, 35)